# Generated by Django 5.0.8 on 2024-08-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
                ('motor', models.CharField(max_length=50, unique=True)),
                ('cilindrada', models.IntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placas', to='vehiculos.vehiculo')),
            ],
        ),
    ]
