# Generated by Django 5.0.8 on 2024-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='dueno',
            field=models.CharField(default='Dueño', max_length=50),
        ),
    ]
